# Generated by Django 3.1.1 on 2020-12-23 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20201223_1345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='publish_date',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='updated',
        ),
    ]
