# Generated by Django 3.1.1 on 2020-12-23 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20201224_0037'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-pk', '-publish_date', '-timestamp', '-updated']},
        ),
    ]
