# Generated by Django 3.1.1 on 2020-12-23 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20201223_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='publish_date',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='updated',
        ),
    ]
