# Generated by Django 3.1.1 on 2020-12-23 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20201223_1405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='updated',
        ),
    ]
